### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by pepa65** [GrainyTV/PngCompressor#1]
After cloning, I first tried `zig build` but that was not right. Then I tried the command in `compile.txt` but that also gave an error: `FileNotFound`.

**Comment by GrainyTV** [comment]
Hi,
Thanks for showing interest in the repository. I never imagined someone would actually want to try out one of my projects. Basically, all my repositories that do not have an associated README.md file are in a somewhat broken state (like this one). The compile.txt was from the first time I used Zig, and I didn't know it had its own build system. But the source code also has some major issues; that's why it did not work for you. Now, all in all, what I am trying to say is that whenever I had free time this past week, I was working on fixing these major issues with the repository, and I can say that now you can try it and it will be a much more pleasant experience. There are still some issues with the command parsing, and the application is currently single-threaded, so it won't be the fastest if you want to compress thousands of images, but it should work in theory.

**Comment by pepa65** [comment]
Thank you for all your efforts. It does compile now..! But it segfaults immediately...

**Comment by GrainyTV** [comment]
I am back again. I was kind of busy with my exam period, but I did not forget about this repo and the issue you had opened. I pushed the latest version to Github, which should have a lot better input parsing than the previous one had. So in theory, it should not segfault. The exception messages were also changed to be more verbose and easier to understand.

**Comment by pepa65** [comment]
It fully works now! Thank you.
